var annotated_dup =
[
    [ "BitmapHandler", "class_bitmap_handler.html", "class_bitmap_handler" ],
    [ "Cube", "class_cube.html", "class_cube" ],
    [ "CubeTextured", "class_cube_textured.html", "class_cube_textured" ],
    [ "DirectDraw", "class_direct_draw.html", "class_direct_draw" ],
    [ "DisplayManager", "class_display_manager.html", "class_display_manager" ],
    [ "Engine", "class_engine.html", "class_engine" ],
    [ "EngineObject", "class_engine_object.html", "class_engine_object" ],
    [ "FigureE", "class_figure_e.html", "class_figure_e" ],
    [ "Figures", "class_figures.html", "class_figures" ],
    [ "IndiceDraw", "class_indice_draw.html", "class_indice_draw" ],
    [ "KeyboardHandler", "class_keyboard_handler.html", "class_keyboard_handler" ],
    [ "Line", "class_line.html", "class_line" ],
    [ "MouseHandler", "class_mouse_handler.html", "class_mouse_handler" ],
    [ "ObjectManager", "class_object_manager.html", "class_object_manager" ],
    [ "Observer", "class_observer.html", "class_observer" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Point", "class_point.html", "class_point" ],
    [ "PoliLine", "class_poli_line.html", "class_poli_line" ],
    [ "Quads", "class_quads.html", "class_quads" ],
    [ "QuadsTextured", "class_quads_textured.html", "class_quads_textured" ],
    [ "Refreshable", "class_refreshable.html", "class_refreshable" ],
    [ "Renderer", "class_renderer.html", "class_renderer" ],
    [ "Resizable", "class_resizable.html", "class_resizable" ],
    [ "Shader", "class_shader.html", "class_shader" ],
    [ "Textured", "class_textured.html", "class_textured" ],
    [ "TransformableFigure", "class_transformable_figure.html", "class_transformable_figure" ],
    [ "Triangle", "class_triangle.html", "class_triangle" ],
    [ "TriangleFan", "class_triangle_fan.html", "class_triangle_fan" ],
    [ "TriangleStrip", "class_triangle_strip.html", "class_triangle_strip" ]
];