var files_dup =
[
    [ "BitmapHandler.h", "_bitmap_handler_8h_source.html", null ],
    [ "Cube.h", "_cube_8h_source.html", null ],
    [ "CubeTextured.h", "_cube_textured_8h_source.html", null ],
    [ "DirectDraw.h", "_direct_draw_8h_source.html", null ],
    [ "DisplayManager.h", "_display_manager_8h_source.html", null ],
    [ "Engine.h", "_engine_8h_source.html", null ],
    [ "EngineObject.h", "_engine_object_8h_source.html", null ],
    [ "FigureE.h", "_figure_e_8h_source.html", null ],
    [ "Figures.h", "_figures_8h_source.html", null ],
    [ "IndiceDraw.h", "_indice_draw_8h_source.html", null ],
    [ "KeyboardHandler.h", "_keyboard_handler_8h_source.html", null ],
    [ "Line.h", "_line_8h_source.html", null ],
    [ "MouseHandler.h", "_mouse_handler_8h_source.html", null ],
    [ "ObjectManager.h", "_object_manager_8h_source.html", null ],
    [ "Observer.h", "_observer_8h_source.html", null ],
    [ "Player.h", "_player_8h_source.html", null ],
    [ "Point.h", "_point_8h_source.html", null ],
    [ "PoliLine.h", "_poli_line_8h_source.html", null ],
    [ "Quads.h", "_quads_8h_source.html", null ],
    [ "QuadsTextured.h", "_quads_textured_8h_source.html", null ],
    [ "Refreshable.h", "_refreshable_8h_source.html", null ],
    [ "Renderer.h", "_renderer_8h_source.html", null ],
    [ "Resizable.h", "_resizable_8h_source.html", null ],
    [ "ShaderHandler.h", "_shader_handler_8h_source.html", null ],
    [ "Textured.h", "_textured_8h_source.html", null ],
    [ "TransformableFigure.h", "_transformable_figure_8h_source.html", null ],
    [ "Triangle.h", "_triangle_8h_source.html", null ],
    [ "TriangleFan.h", "_triangle_fan_8h_source.html", null ],
    [ "TriangleStrip.h", "_triangle_strip_8h_source.html", null ]
];